<?php

/*

e1z4r13p9% curl -c cook.txt 'http://localhost:8888/42_piscine_c_formation_piscine_php_day_03/ex03/cookie_crisp.php?action=set&name=plat&value=choucroute'
e1z4r13p9% cat cook.txt
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/42_piscine_c_formation_piscine_php_day_03/ex03/	FALSE	1538717440	plat	choucroute
e1z4r13p9% curl -b cook.txt 'http://localhost:8888/42_piscine_c_formation_piscine_php_day_03/ex03/cookie_crisp.php?action=get&name=plat'
choucroute
e1z4r13p9% curl -c cook.txt 'http://localhost:8888/42_piscine_c_formation_piscine_php_day_03/ex03/cookie_crisp.php?action=del&name=plat'
e1z4r13p9% cat cook.txt
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/42_piscine_c_formation_piscine_php_day_03/ex03/	FALSE	1538713875	plat	deleted
e1z4r13p9% curl -b cook.txt 'http://localhost:8888/42_piscine_c_formation_piscine_php_day_03/ex03/cookie_crisp.php?action=get&name=plat'

e1z4r13p9%

 */



$action = '';
if (isset($_GET['action']))
	$action = $_GET['action'];

$name = '';
if (isset($_GET['name']))
	$name = $_GET['name'];

$value = '';
if (isset($_GET['value']))
	$value = $_GET['value'];

if (strcmp($action, "set") == 0) {
	if (strlen($name) > 0) {
		setcookie($name, $value, time() + 3600);
	}
}

if (strcmp($action, "del") == 0) {
	if (strlen($name) > 0) {
		setcookie($name, '', time() - 3600);
	}
}

if (strcmp($action, "get") == 0) {
	if (strlen($name) > 0) {
		echo $_COOKIE[$name] . "\n";
	}
}

?>
